-- insert into top250_film values (1, 'Побег из Шоушенка ');
-- insert into top250_film values (2, 'Крёстный отец ');
-- insert into top250_film values (3, 'Крёстный отец 2 ');
-- insert into top250_film values (4, 'Тёмный рыцарь ');
insert into top250_film values (5, '12 разгневанных мужчин ');
insert into top250_film values (6, 'Список Шиндлера ');
insert into top250_film values (7, 'Властелин колец: Возвращение короля ');
insert into top250_film values (8, 'Криминальное чтиво ');
insert into top250_film values (9, 'Хороший, плохой, злой ');
insert into top250_film values (10, 'Властелин колец: Братство Кольца ');
insert into top250_film values (11, 'Бойцовский клуб ');
insert into top250_film values (12, 'Форрест Гамп ');
insert into top250_film values (13, 'Начало ');
insert into top250_film values (14, 'Властелин колец: Две крепости ');
insert into top250_film values (15, 'Звёздные войны. Эпизод V: Империя наносит ответный удар ');
insert into top250_film values (16, 'Матрица ');
insert into top250_film values (17, 'Славные парни ');
insert into top250_film values (18, 'Пролетая над гнездом кукушки ');
insert into top250_film values (19, 'Семь самураев ');
insert into top250_film values (20, 'Семь ');
insert into top250_film values (21, 'Молчание ягнят ');
insert into top250_film values (22, 'Город Бога ');
insert into top250_film values (23, 'Жизнь прекрасна ');
insert into top250_film values (24, 'Эта прекрасная жизнь ');
insert into top250_film values (25, 'Звёздные войны. Эпизод IV: Новая надежда ');
insert into top250_film values (26, 'Спасти рядового Райана ');
insert into top250_film values (27, 'Зелёная миля ');
insert into top250_film values (28, 'Унесённые призраками ');
insert into top250_film values (29, 'Интерстеллар ');
insert into top250_film values (30, 'Паразиты ');
insert into top250_film values (31, 'Леон ');
insert into top250_film values (32, 'Харакири ');
insert into top250_film values (33, 'Подозрительные лица ');
insert into top250_film values (34, 'Король Лев ');
insert into top250_film values (35, 'Пианист ');
insert into top250_film values (36, 'Терминатор 2: Судный день ');
insert into top250_film values (37, 'Назад в будущее ');
insert into top250_film values (38, 'Американская история Икс ');
insert into top250_film values (39, 'Новые времена ');
insert into top250_film values (40, 'Гладиатор ');
insert into top250_film values (41, 'Психо ');
insert into top250_film values (42, 'Отступники ');
insert into top250_film values (43, 'Огни большого города ');
insert into top250_film values (44, '1+1 ');
insert into top250_film values (45, 'Одержимость ');
insert into top250_film values (46, 'Могила светлячков ');
insert into top250_film values (47, 'Престиж ');
insert into top250_film values (48, 'Однажды на Диком Западе ');
insert into top250_film values (49, 'Касабланка ');
insert into top250_film values (50, 'Новый кинотеатр «Парадизо» ');
insert into top250_film values (51, 'Окно во двор ');
insert into top250_film values (52, 'Чужой ');
insert into top250_film values (53, 'Апокалипсис сегодня ');
insert into top250_film values (54, 'Помни ');
insert into top250_film values (55, 'Великий диктатор ');
insert into top250_film values (56, 'Индиана Джонс: В поисках утраченного ковчега ');
insert into top250_film values (57, 'Джанго освобождённый ');
insert into top250_film values (58, 'Жизнь других ');
insert into top250_film values (59, 'Гамильтон ');
insert into top250_film values (60, 'Тропы славы ');
insert into top250_film values (61, 'Джокер ');
insert into top250_film values (62, 'ВАЛЛ-И ');
insert into top250_film values (63, 'Сияние ');
insert into top250_film values (64, 'Мстители: Война бесконечности ');
insert into top250_film values (65, 'Бульвар Сансет ');
insert into top250_film values (66, 'Свидетель обвинения ');
insert into top250_film values (67, 'Олдбой ');
insert into top250_film values (68, 'Человек-паук: Через вселенные ');
insert into top250_film values (69, 'Принцесса Мононоке ');
insert into top250_film values (70, 'Доктор Стрейнджлав, или Как я перестал бояться и полюбил бомбу ');
insert into top250_film values (71, 'Тёмный рыцарь: Возрождение легенды ');
insert into top250_film values (72, 'Однажды в Америке ');
insert into top250_film values (73, 'Твоё имя ');
insert into top250_film values (74, 'Чужие ');
insert into top250_film values (75, 'Тайна Коко ');
insert into top250_film values (76, 'Мстители: Финал ');
insert into top250_film values (77, 'Капернаум ');
insert into top250_film values (78, 'Красота по-американски ');
insert into top250_film values (79, 'Храброе сердце ');
insert into top250_film values (80, 'Рай и ад ');
insert into top250_film values (81, 'Подводная лодка ');
insert into top250_film values (82, 'История игрушек ');
insert into top250_film values (83, '3 идиота ');
insert into top250_film values (84, 'Амадей ');
insert into top250_film values (85, 'Бесславные ублюдки ');
insert into top250_film values (86, 'Умница Уилл Хантинг ');
insert into top250_film values (87, 'Звёздные войны. Эпизод VI: Возвращение джедая ');
insert into top250_film values (88, 'Звёздочки на земле ');
insert into top250_film values (89, 'Бешеные псы ');
insert into top250_film values (90, 'Космическая одиссея 2001 года ');
insert into top250_film values (91, 'Реквием по мечте ');
insert into top250_film values (92, 'Охота ');
insert into top250_film values (93, 'Головокружение ');
insert into top250_film values (94, 'М ');
insert into top250_film values (95, 'Вечное сияние чистого разума ');
insert into top250_film values (96, 'Гражданин Кейн ');
insert into top250_film values (97, 'Дангал ');
insert into top250_film values (98, 'Лига справедливости Зака Снайдера ');
insert into top250_film values (0, '0 ');
insert into top250_film values (99, 'Поющие под дождём ');
insert into top250_film values (100, 'Малыш ');
insert into top250_film values (101, 'Похитители велосипедов ');
insert into top250_film values (102, 'Цельнометаллическая оболочка ');
insert into top250_film values (103, 'Иди и смотри ');
insert into top250_film values (104, 'Жить ');
insert into top250_film values (105, 'Большой куш ');
insert into top250_film values (106, 'К северу через северо-запад ');
insert into top250_film values (107, 'Заводной апельсин ');
insert into top250_film values (108, 'Лицо со шрамом ');
insert into top250_film values (109, '1917 ');
insert into top250_film values (110, 'Таксист ');
insert into top250_film values (111, 'Пожары ');
insert into top250_film values (112, 'Развод Надера и Симин ');
insert into top250_film values (113, 'История игрушек: Большой побег ');
insert into top250_film values (114, 'Лоуренс Аравийский ');
insert into top250_film values (115, 'Афера ');
insert into top250_film values (116, 'Амели ');
insert into top250_film values (117, 'Метрополис ');
insert into top250_film values (118, 'Квартира ');
insert into top250_film values (119, 'На несколько долларов больше ');
insert into top250_film values (120, 'Двойная страховка ');
insert into top250_film values (121, 'Убить пересмешника ');
insert into top250_film values (122, 'Вверх ');
insert into top250_film values (123, 'Индиана Джонс и последний крестовый поход ');
insert into top250_film values (124, 'Схватка ');
insert into top250_film values (125, 'Секреты Лос-Анджелеса ');
insert into top250_film values (126, 'Зелёная книга ');
insert into top250_film values (127, 'Крепкий орешек ');
insert into top250_film values (128, 'Бэтмен: Начало ');
insert into top250_film values (129, 'Монти Пайтон и Священный Грааль ');
insert into top250_film values (130, 'Телохранитель ');
insert into top250_film values (131, 'Расёмон ');
insert into top250_film values (132, 'Бункер ');
insert into top250_film values (133, 'Дети небес ');
insert into top250_film values (134, 'Ран ');
insert into top250_film values (135, 'Непрощённый ');
insert into top250_film values (136, 'В джазе только девушки ');
insert into top250_film values (137, 'Ходячий замок ');
insert into top250_film values (138, 'Всё о Еве ');
insert into top250_film values (139, 'Казино ');
insert into top250_film values (140, 'Игры разума ');
insert into top250_film values (141, 'Волк с Уолл-стрит ');
insert into top250_film values (142, 'Большой побег ');
insert into top250_film values (143, 'Лабиринт фавна ');
insert into top250_film values (144, 'Нефть ');
insert into top250_film values (145, 'Тайна в его глазах ');
insert into top250_film values (146, 'Карты, деньги, два ствола ');
insert into top250_film values (147, 'Нюрнбергский процесс ');
insert into top250_film values (148, 'Бешеный бык ');
insert into top250_film values (149, 'Мой сосед Тоторо ');
insert into top250_film values (150, 'Сокровища Сьерра-Мадре ');
insert into top250_film values (151, 'В случае убийства набирайте «М» ');
insert into top250_film values (152, 'Три билборда на границе Эббинга, Миссури ');
insert into top250_film values (153, 'Остров проклятых ');
insert into top250_film values (154, 'Китайский квартал ');
insert into top250_film values (155, 'Золотая лихорадка ');
insert into top250_film values (156, 'Мой отец и мой сын ');
insert into top250_film values (157, 'Старикам тут не место ');
insert into top250_film values (158, 'V — значит вендетта ');
insert into top250_film values (159, 'Головоломка ');
insert into top250_film values (160, 'Нечто ');
insert into top250_film values (161, 'Человек-слон ');
insert into top250_film values (162, 'Седьмая печать ');
insert into top250_film values (163, 'Воин ');
insert into top250_film values (164, 'Шестое чувство ');
insert into top250_film values (165, 'Парк юрского периода ');
insert into top250_film values (166, 'Клаус ');
insert into top250_film values (167, 'На игле ');
insert into top250_film values (168, 'Шоу Трумана ');
insert into top250_film values (169, 'Унесённые ветром ');
insert into top250_film values (170, 'В поисках Немо ');
insert into top250_film values (171, 'Сталкер ');
insert into top250_film values (172, 'Земляничная поляна ');
insert into top250_film values (173, 'Воспоминания об убийстве ');
insert into top250_film values (174, 'Убить Билла. Фильм 1 ');
insert into top250_film values (175, 'Бегущий по лезвию ');
insert into top250_film values (176, 'Мост через реку Квай ');
insert into top250_film values (177, 'Фарго ');
insert into top250_film values (178, 'Комната ');
insert into top250_film values (179, 'Дикие истории ');
insert into top250_film values (180, 'Токийская повесть ');
insert into top250_film values (181, 'Гран Торино ');
insert into top250_film values (182, 'Третий человек ');
insert into top250_film values (183, 'В порту ');
insert into top250_film values (184, 'Охотник на оленей ');
insert into top250_film values (185, 'Во имя отца ');
insert into top250_film values (186, 'Мэри и Макс ');
insert into top250_film values (187, 'Отель «Гранд Будапешт» ');
insert into top250_film values (188, 'Перед рассветом ');
insert into top250_film values (189, 'Поймай меня, если сможешь ');
insert into top250_film values (190, 'Исчезнувшая ');
insert into top250_film values (191, 'По соображениям совести ');
insert into top250_film values (192, 'Пленницы ');
insert into top250_film values (193, 'Персона ');
insert into top250_film values (194, 'Стреляйте в пианиста ');
insert into top250_film values (195, 'Шерлок-младший ');
insert into top250_film values (196, 'Большой Лебовски ');
insert into top250_film values (197, 'Барри Линдон ');
insert into top250_film values (198, 'Быть или не быть ');
insert into top250_film values (199, 'Генерал ');
insert into top250_film values (200, 'Как приручить дракона ');
insert into top250_film values (201, 'Ford против Ferrari ');
insert into top250_film values (202, '12 лет рабства ');
insert into top250_film values (203, 'Осенняя соната ');
insert into top250_film values (204, 'Бандит ');
insert into top250_film values (205, 'Мистер Смит едет в Вашингтон ');
insert into top250_film values (206, 'Ананд ');
insert into top250_film values (207, 'Безумный Макс: Дорога ярости ');
insert into top250_film values (208, 'Общество мёртвых поэтов ');
insert into top250_film values (209, 'Малышка на миллион ');
insert into top250_film values (210, 'Гарри Поттер и Дары Смерти. Часть 2 ');
insert into top250_film values (211, 'Останься со мной ');
insert into top250_film values (212, 'Телесеть ');
insert into top250_film values (213, 'Бен-Гур ');
insert into top250_film values (214, 'Хатико: Самый верный друг ');
insert into top250_film values (215, 'Золушка ');
insert into top250_film values (216, 'Служанка ');
insert into top250_film values (217, 'Хладнокровный Люк ');
insert into top250_film values (218, 'Логан ');
insert into top250_film values (219, 'Взвод ');
insert into top250_film values (220, 'В диких условиях ');
insert into top250_film values (221, 'Плата за страх ');
insert into top250_film values (222, 'Гонка ');
insert into top250_film values (223, 'Ненависть ');
insert into top250_film values (224, 'Житие Брайана по Монти Пайтону ');
insert into top250_film values (225, 'Четыреста ударов ');
insert into top250_film values (226, 'Страсти Жанны д’Арк ');
insert into top250_film values (227, 'В центре внимания ');
insert into top250_film values (228, 'Душа ');
insert into top250_film values (229, 'Отель Руанда ');
insert into top250_film values (230, 'Банды Вассейпура ');
insert into top250_film values (231, 'Сука любовь ');
insert into top250_film values (232, 'Андрей Рублёв ');
insert into top250_film values (233, 'Корпорация монстров ');
insert into top250_film values (234, 'Рокки ');
insert into top250_film values (235, 'Навсикая из Долины ветров ');
insert into top250_film values (236, 'Ребекка ');
insert into top250_film values (237, 'Время цыган ');
insert into top250_film values (238, 'Перед закатом ');
insert into top250_film values (239, 'Любовное настроение ');
insert into top250_film values (240, 'Мужские разборки ');
insert into top250_film values (241, 'Цвет шафрана ');
insert into top250_film values (242, 'Париж, Техас ');
insert into top250_film values (243, 'Видимость ');
insert into top250_film values (244, 'Портрет девушки в огне ');
insert into top250_film values (245, 'Это случилось однажды ночью ');
insert into top250_film values (246, 'Конец Евангелиона ');
insert into top250_film values (247, 'Форма голоса ');
insert into top250_film values (248, 'Видимость ');
insert into top250_film values (249, 'Возвращение на Родину ');
insert into top250_film values (250, 'Невидимый гость ');
