telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://quiet-lowlands-60625.herokuapp.com/"
  bot-name: "@Stiraralka_bot"
  bot-token: "5121364075:AAG4ybOP_vUKF6ovnd-RkrGzpPHEbUBgwSE"
spring:
  datasource:
    url: jdbc:postgresql://ec2-3-223-213-207.compute-1.amazonaws.com:5432/d2k7sd44bv9qk?user=yibwakhuejhvlz&password=885252de5303d1f3899719bb9a7aee0988b330db56ad8b6cbd08a7ad1c8cf35d
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update