telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://quiet-lowlands-60625.herokuapp.com/"
  bot-name: "@Stiraralka_bot"
  bot-token: "5121364075:AAG4ybOP_vUKF6ovnd-RkrGzpPHEbUBgwSE"